# Site settings
# title: RoR Tutorials
# email: przbadu.social@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "/tutorials"
# url: "http://przbadu-pages.github.io" # the base hostname & protocol for your site

# # Build settings
# markdown: kramdown
# twitter_username: przbadu
# github_username:  przbadu


markdown: kramdown
baseurl: "/tutorials"
url: "http://przbadu-pages.github.io"
exclude: ['README.md']
